In [1]:
from __future__ import absolute_import, division, print_function, unicode_literals
import pathlib
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import normalize
from keras import Sequential
import matplotlib.pyplot as plt

# Neuer Abschnitt

In [2]:
pip install git+https://github.com/tensorflow/docs

  Cloning https://github.com/tensorflow/docs to /tmp/pip-req-build-93v4b_2y
  Running command git clone -q https://github.com/tensorflow/docs /tmp/pip-req-build-93v4b_2y
  Created wheel for tensorflow-docs: filename=tensorflow_docs-0.0.0dcf6d428a23727780cedcb671ebd9791b1b6f106_-cp36-none-any.whl size=133393 sha256=c29ec3b716da18fc9da2aa897847c63597e100559407afc4f91716b9e0ad062d
  Stored in directory: /tmp/pip-ephem-wheel-cache-w7gazu62/wheels/eb/1b/35/fce87697be00d2fc63e0b4b395b0d9c7e391a10e98d9a0d97f
Successfully built tensorflow-docs


In [3]:
import tensorflow_docs as tfdocs
import tensorflow_docs.plots
import tensorflow_docs.modeling

In [5]:
# Upload Daten_redWine_21.csv to Colaboratory files ("Upload to session storage")
df=pd.read_csv('/content/Daten_redWine_21.CSV')

In [ ]:
print(df)

      fixedacidity  volatileacidity  citricacid  ...  sulphates  alcohol  quality
0              7.0             0.27        0.36  ...       0.45      8.8        6
1              6.3             0.30        0.34  ...       0.49      9.5        6
2              8.1             0.28        0.40  ...       0.44     10.1        6
3              7.2             0.23        0.32  ...       0.40      9.9        6
4              7.2             0.23        0.32  ...       0.40      9.9        6
...            ...              ...         ...  ...        ...      ...      ...
4892           6.5             0.23        0.38  ...       0.54      9.7        5
4893           6.2             0.21        0.29  ...       0.50     11.2        6
4894           6.6             0.32        0.36  ...       0.46      9.6        5
4895           6.5             0.24        0.19  ...       0.46      9.4        6
4896           5.5             0.29        0.30  ...       0.38     12.8        7

[4897 rows x 12

In [6]:
df['quality'].mean()

5.8778844190320605

In [7]:
training_dataset = df.sample(frac=0.8,random_state=0)
test_dataset = df.drop(training_dataset.index)

In [8]:
training_labels = training_dataset.pop('quality')
test_labels = test_dataset.pop('quality')

In [9]:
normalized_training_data = normalize(training_dataset)
normalized_test_data = normalize(test_dataset)

In [10]:
print(training_dataset)

      fixedacidity  volatileacidity  citricacid  ...    pH  sulphates  alcohol
2762           7.3             0.32        0.35  ...  3.24       0.42     10.7
42             7.0             0.31        0.26  ...  3.13       0.46      9.8
1419           7.6             0.14        0.74  ...  3.07       0.40     10.8
3664           5.0             0.29        0.54  ...  3.27       0.34     12.9
2125           6.0             0.28        0.22  ...  3.20       0.46     10.1
...            ...              ...         ...  ...   ...        ...      ...
2845           6.5             0.22        0.29  ...  3.15       0.56     10.9
3384           6.8             0.23        0.30  ...  3.25       0.56     10.6
2056           6.8             0.21        0.27  ...  3.30       0.36      8.7
4016           7.2             0.40        0.24  ...  3.20       0.52      9.2
1622           6.5             0.44        0.49  ...  3.11       0.37      8.7

[3918 rows x 11 columns]


In [11]:
print(normalized_training_data)

[[0.04457968 0.00195418 0.00213738 ... 0.01978605 0.00256486 0.06534282]
 [0.04292381 0.00190091 0.00159431 ... 0.01919308 0.00282071 0.06009334]
 [0.07079009 0.00130403 0.00689272 ... 0.02859547 0.00372579 0.10059644]
 ...
 [0.04439564 0.00137104 0.00176277 ... 0.02154495 0.00235036 0.05680031]
 [0.04549455 0.00252748 0.00151649 ... 0.0202198  0.00328572 0.05813193]
 [0.03816572 0.00258353 0.00287711 ... 0.01826083 0.00217251 0.05108335]]


In [12]:
print(normalized_training_data.shape)

(3918, 11)


In [45]:
# Try adding more Dense layers between these two with activation='relu', differing number of neurons

model = keras.Sequential([
    layers.Dense(64, activation='relu', input_shape=[len(training_dataset.keys())]),
    layers.Dense(128, activation='relu', input_shape=[len(training_dataset.keys())]),
    layers.Dense(128, activation='relu', input_shape=[len(training_dataset.keys())]),
    layers.Dense(100, activation='relu', input_shape=[len(training_dataset.keys())]),
    layers.Dense(10, activation='softmax', input_shape=[len(training_dataset.keys())]),
    layers.Dense(1)
  ])

model.compile(loss='mse',
              optimizer='adam',
              metrics=['mae', 'mse', 'accuracy'])

In [46]:
len(training_dataset.keys())

11

In [47]:
print(model.summary())

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_17 (Dense)             (None, 64)                768       
_________________________________________________________________
dense_18 (Dense)             (None, 128)               8320      
_________________________________________________________________
dense_19 (Dense)             (None, 128)               16512     
_________________________________________________________________
dense_20 (Dense)             (None, 100)               12900     
_________________________________________________________________
dense_21 (Dense)             (None, 10)                1010      
_________________________________________________________________
dense_22 (Dense)             (None, 1)                 11        
Total params: 39,521
Trainable params: 39,521
Non-trainable params: 0
__________________________________________________

In [48]:
print(normalized_training_data)
print(normalized_training_data.shape)

[[0.04457968 0.00195418 0.00213738 ... 0.01978605 0.00256486 0.06534282]
 [0.04292381 0.00190091 0.00159431 ... 0.01919308 0.00282071 0.06009334]
 [0.07079009 0.00130403 0.00689272 ... 0.02859547 0.00372579 0.10059644]
 ...
 [0.04439564 0.00137104 0.00176277 ... 0.02154495 0.00235036 0.05680031]
 [0.04549455 0.00252748 0.00151649 ... 0.0202198  0.00328572 0.05813193]
 [0.03816572 0.00258353 0.00287711 ... 0.01826083 0.00217251 0.05108335]]
(3918, 11)


In [49]:
EPOCHS = 1000 # changed from 1000 to 100

history = model.fit(
  normalized_training_data, training_labels,
  epochs=EPOCHS, validation_split = 0.0005, verbose=0, #changed the spilt from 0.2 to 0.0005
  callbacks=[tfdocs.modeling.EpochDots()])


Epoch: 0, accuracy:0.0000,  loss:29.5383,  mae:5.3546,  mse:29.5383,  val_accuracy:0.0000,  val_loss:22.5529,  val_mae:4.7226,  val_mse:22.5529,  
....................................................................................................
Epoch: 100, accuracy:0.0000,  loss:0.7875,  mae:0.6747,  mse:0.7875,  val_accuracy:0.0000,  val_loss:0.3866,  val_mae:0.5000,  val_mse:0.3866,  
....................................................................................................
Epoch: 200, accuracy:0.0000,  loss:0.7873,  mae:0.6704,  mse:0.7873,  val_accuracy:0.0000,  val_loss:0.3864,  val_mae:0.5000,  val_mse:0.3864,  
....................................................................................................
Epoch: 300, accuracy:0.0000,  loss:0.7875,  mae:0.6724,  mse:0.7875,  val_accuracy:0.0000,  val_loss:0.3991,  val_mae:0.5000,  val_mse:0.3991,  
....................................................................................................
Epoch: 400, a

In [50]:
x = pd.read_csv('/content/Neu2.csv')

In [51]:
print(x)

   fixedacidity  volatileacidity  citricacid  ...  sulphates  alcohol  quality
0           4.4             0.32        0.39  ...       0.36     12.8        8

[1 rows x 12 columns]


In [52]:
x.pop('quality')

0    8
Name: quality, dtype: int64

In [53]:
print(x)

   fixedacidity  volatileacidity  citricacid  ...    pH  sulphates  alcohol
0           4.4             0.32        0.39  ...  3.46       0.36     12.8

[1 rows x 11 columns]


In [54]:
normalize(x)

array([[3.34477234e-02, 2.43256170e-03, 2.96468458e-03, 3.26875479e-02,
        2.28052660e-04, 2.35654415e-01, 9.65422926e-01, 7.51844009e-03,
        2.63020734e-02, 2.73663192e-03, 9.73024682e-02]])

In [55]:
prediction = model.predict(x)
print(int(prediction))

5


In [56]:
normalize(prediction)

array([[1.]], dtype=float32)

In [57]:
print(int(prediction))

5


In [58]:
evaluation_ds = pd.read_csv('/content/evaluation_data.CSV')

FileNotFoundError: ignored

In [ ]:
print(evaluation_ds)

    fixed acidity  volatile acidity  citric acid  ...  alcohol  quality  Type
0             6.2             0.250         0.38  ...      9.1        5     1
1             7.1             0.280         0.35  ...     12.1        5     1
2             6.6             0.350         0.34  ...     12.0        5     1
3             8.5             0.190         0.48  ...     10.5        6     1
4             6.2             0.250         0.54  ...     10.4        5     1
5             6.0             0.350         0.51  ...     11.9        6     1
6             5.8             0.310         0.32  ...     13.7        7     1
7            10.4             0.430         0.50  ...     11.4        6     0
8             6.9             0.410         0.31  ...      9.5        6     0
9             5.5             0.490         0.03  ...     14.0        8     0
10            5.0             0.380         0.01  ...     14.0        6     0
11            7.3             0.440         0.20  ...     11.7  

In [ ]:
evaluation_ds.pop('quality')

0     5
1     5
2     5
3     6
4     5
5     6
6     7
7     6
8     6
9     8
10    6
11    6
12    5
13    5
14    6
15    6
16    5
17    6
18    6
19    6
20    6
21    5
Name: quality, dtype: int64

In [ ]:
print("Evaluate on test data")
results = model.evaluate(evaluation_ds, batch_size = 1)
print("test loss, test acc:", results)

Evaluate on test data


ValueError: ignored