In [277]:
from __future__ import absolute_import, division, print_function, unicode_literals
import pathlib
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import normalize
from keras import Sequential
import matplotlib.pyplot as plt

# Neuer Abschnitt

In [278]:
pip install git+https://github.com/tensorflow/docs

  Cloning https://github.com/tensorflow/docs to /tmp/pip-req-build-m9xg6m8c
  Running command git clone -q https://github.com/tensorflow/docs /tmp/pip-req-build-m9xg6m8c
  Created wheel for tensorflow-docs: filename=tensorflow_docs-0.0.0dcf6d428a23727780cedcb671ebd9791b1b6f106_-cp36-none-any.whl size=133393 sha256=12b1a3abfd52ebe4ce81fa52f8f6a415b58ec25c5a63aacf16651abbcc472fc3
  Stored in directory: /tmp/pip-ephem-wheel-cache-3kemfboi/wheels/eb/1b/35/fce87697be00d2fc63e0b4b395b0d9c7e391a10e98d9a0d97f
Successfully built tensorflow-docs


In [279]:
import tensorflow_docs as tfdocs
import tensorflow_docs.plots
import tensorflow_docs.modeling

In [280]:
# Upload Daten_redWine_21.csv to Colaboratory files ("Upload to session storage")
df=pd.read_csv('/content/FINAL.CSV')

In [281]:
print(df)

      fixed acidity  volatile acidity  citric acid  ...  alcohol  quality  Type
0               7.4              0.70         0.00  ...      9.4        5     0
1               7.8              0.88         0.00  ...      9.8        5     0
2               7.8              0.76         0.04  ...      9.8        5     0
3              11.2              0.28         0.56  ...      9.8        6     0
4               7.4              0.70         0.00  ...      9.4        5     0
...             ...               ...          ...  ...      ...      ...   ...
6492            6.2              0.21         0.29  ...     11.2        6     1
6493            6.6              0.32         0.36  ...      9.6        5     1
6494            6.5              0.24         0.19  ...      9.4        6     1
6495            5.5              0.29         0.30  ...     12.8        7     1
6496            6.0              0.21         0.38  ...     11.8        6     1

[6497 rows x 13 columns]


In [282]:
df['Type'].mean()

0.7538864091118977

In [283]:
training_dataset = df.sample(frac=0.8,random_state=0)
test_dataset = df.drop(training_dataset.index)

In [284]:
training_labels = training_dataset.pop('Type')
test_labels = test_dataset.pop('Type')

In [285]:
normalized_training_data = normalize(training_dataset)
normalized_test_data = normalize(test_dataset)

In [286]:
print(training_dataset)

      fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
5316            6.3             0.180         0.24  ...       0.52      9.2        6
5210            6.8             0.140         0.18  ...       0.54     11.2        6
3518            7.3             0.220         0.50  ...       0.66      9.0        6
1622            7.6             0.670         0.14  ...       0.51      9.3        5
2443            7.3             0.210         0.29  ...       0.50     11.0        8
...             ...               ...          ...  ...        ...      ...      ...
5668            6.2             0.240         0.28  ...       0.37     10.7        6
239             8.2             1.000         0.09  ...       0.55      9.0        6
5786            5.9             0.240         0.34  ...       0.50     12.3        6
542             9.3             0.715         0.24  ...       0.59      9.9        5
2725            6.5             0.115         0.29  ...       0.2

In [287]:
print(normalized_training_data)

[[0.05188409 0.0014824  0.00197654 ... 0.0042825  0.07576724 0.04941342]
 [0.07081158 0.00145789 0.00187442 ... 0.00562327 0.11663084 0.06248081]
 [0.03685778 0.00111078 0.00252451 ... 0.00333235 0.04544109 0.03029406]
 ...
 [0.05077596 0.00206546 0.00292607 ... 0.00430305 0.10585496 0.05163657]
 [0.36461914 0.02803255 0.00940953 ... 0.02313175 0.38814295 0.19603179]
 [0.03569633 0.00063155 0.00159261 ... 0.00137294 0.07084348 0.0384422 ]]


In [288]:
print(normalized_training_data.shape)

(5198, 12)


In [289]:
# Try adding more Dense layers between these two with activation='relu', differing number of neurons

model = keras.Sequential([
    layers.Dense(64, activation='relu', input_shape=[len(training_dataset.keys())]),
    layers.Dense(128, activation='relu', input_shape=[len(training_dataset.keys())]),
    layers.Dense(128, activation='relu', input_shape=[len(training_dataset.keys())]),
    layers.Dense(100, activation='elu', input_shape=[len(training_dataset.keys())]),
    layers.Dense(10, activation='softmax', input_shape=[len(training_dataset.keys())]),
    layers.Dense(1)
  ])

model.compile(loss='mse',
              optimizer='adam',
              metrics=['mae', 'mse', 'accuracy'])

In [290]:
len(training_dataset.keys())

12

In [291]:
print(model.summary())

Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_36 (Dense)             (None, 64)                832       
_________________________________________________________________
dense_37 (Dense)             (None, 128)               8320      
_________________________________________________________________
dense_38 (Dense)             (None, 128)               16512     
_________________________________________________________________
dense_39 (Dense)             (None, 100)               12900     
_________________________________________________________________
dense_40 (Dense)             (None, 10)                1010      
_________________________________________________________________
dense_41 (Dense)             (None, 1)                 11        
Total params: 39,585
Trainable params: 39,585
Non-trainable params: 0
__________________________________________________

In [292]:
print(normalized_training_data)
print(normalized_training_data.shape)

[[0.05188409 0.0014824  0.00197654 ... 0.0042825  0.07576724 0.04941342]
 [0.07081158 0.00145789 0.00187442 ... 0.00562327 0.11663084 0.06248081]
 [0.03685778 0.00111078 0.00252451 ... 0.00333235 0.04544109 0.03029406]
 ...
 [0.05077596 0.00206546 0.00292607 ... 0.00430305 0.10585496 0.05163657]
 [0.36461914 0.02803255 0.00940953 ... 0.02313175 0.38814295 0.19603179]
 [0.03569633 0.00063155 0.00159261 ... 0.00137294 0.07084348 0.0384422 ]]
(5198, 12)


In [293]:
EPOCHS = 1000 # changed from 1000 to 100

history = model.fit(
  normalized_training_data, training_labels,
  epochs=EPOCHS, validation_split = 0.005, verbose=0, #changed the spilt from 0.2 to 0.005
  callbacks=[tfdocs.modeling.EpochDots()])


Epoch: 0, accuracy:0.7904,  loss:0.1589,  mae:0.3074,  mse:0.1589,  val_accuracy:0.9231,  val_loss:0.0383,  val_mae:0.1399,  val_mse:0.0383,  
....................................................................................................
Epoch: 100, accuracy:0.9853,  loss:0.0117,  mae:0.0241,  mse:0.0117,  val_accuracy:1.0000,  val_loss:0.0012,  val_mae:0.0136,  val_mse:0.0012,  
....................................................................................................
Epoch: 200, accuracy:0.9886,  loss:0.0090,  mae:0.0187,  mse:0.0090,  val_accuracy:1.0000,  val_loss:0.0002,  val_mae:0.0068,  val_mse:0.0002,  
....................................................................................................
Epoch: 300, accuracy:0.9911,  loss:0.0068,  mae:0.0141,  mse:0.0068,  val_accuracy:1.0000,  val_loss:0.0039,  val_mae:0.0169,  val_mse:0.0039,  
....................................................................................................
Epoch: 400, accur

In [294]:
x = pd.read_csv('/content/test.CSV')

In [295]:
print(x)

   fixed acidity  volatile acidity  citric acid  ...  alcohol  quality  Type
0            7.8              0.61         0.29  ...      9.1        5     0

[1 rows x 13 columns]


In [296]:
x.pop('Type')

0    0
Name: Type, dtype: int64

In [297]:
print(x)

   fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0            7.8              0.61         0.29  ...       1.56      9.1        5

[1 rows x 12 columns]


In [298]:
normalize(x)

array([[0.2343563 , 0.01832786, 0.00871325, 0.04807309, 0.00342521,
        0.27041111, 0.87132469, 0.02996756, 0.09794891, 0.04687126,
        0.27341568, 0.15022839]])

In [299]:
prediction = model.predict(
    x, batch_size=1, verbose=0, steps=None, callbacks=None, 
)


In [309]:
normalize(prediction)

array([[1.]], dtype=float32)

In [308]:
print(int(prediction))

0


In [302]:
evaluation_ds = pd.read_csv('/content/evaluation_data.CSV')

In [303]:
print(evaluation_ds)

    fixed acidity  volatile acidity  citric acid  ...  alcohol  quality  Type
0             6.2             0.250         0.38  ...      9.1        5     1
1             7.1             0.280         0.35  ...     12.1        5     1
2             6.6             0.350         0.34  ...     12.0        5     1
3             8.5             0.190         0.48  ...     10.5        6     1
4             6.2             0.250         0.54  ...     10.4        5     1
5             6.0             0.350         0.51  ...     11.9        6     1
6             5.8             0.310         0.32  ...     13.7        7     1
7            10.4             0.430         0.50  ...     11.4        6     0
8             6.9             0.410         0.31  ...      9.5        6     0
9             5.5             0.490         0.03  ...     14.0        8     0
10            5.0             0.380         0.01  ...     14.0        6     0
11            7.3             0.440         0.20  ...     11.7  

In [304]:
evaluation_ds.pop('Type')

0     1
1     1
2     1
3     1
4     1
5     1
6     1
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    1
20    1
21    1
Name: Type, dtype: int64

In [305]:
normalize(evaluation_ds)

array([[2.87827399e-02, 1.16059435e-03, 1.76410341e-03, 3.66747815e-02,
        2.08906983e-04, 2.50688380e-01, 9.65614501e-01, 4.62250803e-03,
        1.47163364e-02, 2.13549361e-03, 4.22456344e-02, 2.32118870e-02],
       [7.19040425e-02, 2.83565238e-03, 3.54456548e-03, 3.54456548e-02,
        2.83565238e-04, 3.54456548e-01, 9.21587024e-01, 1.00282846e-02,
        2.99768966e-02, 3.34201888e-03, 1.22540692e-01, 5.06366497e-02],
       [5.22503372e-02, 2.77085121e-03, 2.69168404e-03, 3.87919170e-02,
        2.53334968e-04, 7.12504598e-02, 9.89589719e-01, 7.85757987e-03,
        2.62835029e-02, 6.41254138e-03, 9.50006131e-02, 3.95835888e-02],
       [1.32383002e-01, 2.95914945e-03, 7.47574598e-03, 1.71319179e-02,
        4.04936240e-04, 3.58212828e-01, 9.03319306e-01, 1.54473831e-02,
        4.51659653e-02, 7.78723539e-03, 1.63531943e-01, 9.34468247e-02],
       [3.33446065e-02, 1.34454059e-03, 2.90420767e-03, 3.76471364e-02,
        2.47395468e-04, 3.11933416e-01, 9.46556572e-01, 5.34

In [306]:
print("Evaluate on test data")
results = model.evaluate(evaluation_ds, batch_size = 1)
print("test loss, test acc:", results)

Evaluate on test data
22/22 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - mae: 0.0000e+00 - mse: 0.0000e+00 - accuracy: 0.0000e+00
test loss, test acc: [0.0, 0.0, 0.0, 0.0]


In [307]:
print(results)

[0.0, 0.0, 0.0, 0.0]
